/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "McuSystemPb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(McuSystemPb_motor_cali_rsp_t, McuSystemPb_motor_cali_rsp_t, AUTO)


PB_BIND(McuSystemPb_band_language_t, McuSystemPb_band_language_t, AUTO)


PB_BIND(McuSystemPb_oobe_notify_t, McuSystemPb_oobe_notify_t, AUTO)


PB_BIND(McuSystemPb_mcu_status, McuSystemPb_mcu_status, AUTO)


PB_BIND(McuSystemPb_enable_mcu_status, McuSystemPb_enable_mcu_status, AUTO)


PB_BIND(McuSystemPb_boot_notify, McuSystemPb_boot_notify, AUTO)


PB_BIND(McuSystemPb_reboot_reason, McuSystemPb_reboot_reason, AUTO)


PB_BIND(McuSystemPb_backlight, McuSystemPb_backlight, AUTO)


PB_BIND(McuSystemPb_screen_rotation, McuSystemPb_screen_rotation, AUTO)


PB_BIND(McuSystemPb_conan_flag_t, McuSystemPb_conan_flag_t, AUTO)


PB_BIND(McuSystemPb_brightness_adapt, McuSystemPb_brightness_adapt, AUTO)


PB_BIND(McuSystemPb_light_cali_rsp_t, McuSystemPb_light_cali_rsp_t, AUTO)



