/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MCUSYSTEMPB_MCUSYSTEMPB_PB_H_INCLUDED
#define PB_MCUSYSTEMPB_MCUSYSTEMPB_PB_H_INCLUDED
#include <pb.h>
#include "SystemTime.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _McuSystemPb_motor_cali_rsp_t {
    bool has_f0Param;
    uint32_t f0Param;
    bool has_caliF0;
    uint32_t caliF0;
    bool has_caliOsc;
    uint32_t caliOsc;
} McuSystemPb_motor_cali_rsp_t;

typedef struct _McuSystemPb_band_language_t {
    bool has_language;
    uint32_t language;
    pb_callback_t phoneMac;
    bool has_needUpdateWeather;
    uint32_t needUpdateWeather;
} McuSystemPb_band_language_t;

typedef struct _McuSystemPb_oobe_notify_t {
    bool has_oobeStatus;
    uint32_t oobeStatus;
    pb_callback_t phoneMac;
    bool has_needUpdateWeather;
    uint32_t needUpdateWeather;
} McuSystemPb_oobe_notify_t;

typedef struct _McuSystemPb_mcu_status {
    bool has_status;
    uint32_t status;
} McuSystemPb_mcu_status;

typedef struct _McuSystemPb_enable_mcu_status {
    bool has_enable;
    uint32_t enable;
} McuSystemPb_enable_mcu_status;

typedef struct _McuSystemPb_boot_notify {
    bool has_type;
    uint32_t type;
    bool has_oobe;
    McuSystemPb_oobe_notify_t oobe;
    bool has_sysTime;
    SystemTime_rsp_read_sys_time_t sysTime;
} McuSystemPb_boot_notify;

typedef struct _McuSystemPb_reboot_reason {
    bool has_reason;
    uint32_t reason;
    bool has_mcuSysTime;
    SystemTime_rsp_read_sys_time_t mcuSysTime;
    bool has_eStatus;
    uint32_t eStatus;
} McuSystemPb_reboot_reason;

typedef struct _McuSystemPb_backlight {
    bool has_c0;
    float c0;
    bool has_c1;
    float c1;
    bool has_time;
    float time;
    bool has_gain;
    float gain;
} McuSystemPb_backlight;

typedef struct _McuSystemPb_screen_rotation {
    bool has_rotation;
    uint32_t rotation;
} McuSystemPb_screen_rotation;

typedef struct _McuSystemPb_conan_flag_t {
    bool has_data;
    uint64_t data;
} McuSystemPb_conan_flag_t;

typedef struct _McuSystemPb_brightness_adapt {
    bool has_brightness;
    uint32_t brightness;
    bool has_lux;
    uint32_t lux;
} McuSystemPb_brightness_adapt;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define McuSystemPb_motor_cali_rsp_t_init_default {false, 0, false, 0, false, 0}
#define McuSystemPb_band_language_t_init_default {false, 0, {{NULL}, NULL}, false, 0}
#define McuSystemPb_oobe_notify_t_init_default   {false, 0, {{NULL}, NULL}, false, 0}
#define McuSystemPb_mcu_status_init_default      {false, 0}
#define McuSystemPb_enable_mcu_status_init_default {false, 0}
#define McuSystemPb_boot_notify_init_default     {false, 0, false, McuSystemPb_oobe_notify_t_init_default, false, SystemTime_rsp_read_sys_time_t_init_default}
#define McuSystemPb_reboot_reason_init_default   {false, 0, false, SystemTime_rsp_read_sys_time_t_init_default, false, 0}
#define McuSystemPb_backlight_init_default       {false, 0, false, 0, false, 0, false, 0}
#define McuSystemPb_screen_rotation_init_default {false, 0}
#define McuSystemPb_conan_flag_t_init_default    {false, 0}
#define McuSystemPb_brightness_adapt_init_default {false, 0, false, 0}
#define McuSystemPb_motor_cali_rsp_t_init_zero   {false, 0, false, 0, false, 0}
#define McuSystemPb_band_language_t_init_zero    {false, 0, {{NULL}, NULL}, false, 0}
#define McuSystemPb_oobe_notify_t_init_zero      {false, 0, {{NULL}, NULL}, false, 0}
#define McuSystemPb_mcu_status_init_zero         {false, 0}
#define McuSystemPb_enable_mcu_status_init_zero  {false, 0}
#define McuSystemPb_boot_notify_init_zero        {false, 0, false, McuSystemPb_oobe_notify_t_init_zero, false, SystemTime_rsp_read_sys_time_t_init_zero}
#define McuSystemPb_reboot_reason_init_zero      {false, 0, false, SystemTime_rsp_read_sys_time_t_init_zero, false, 0}
#define McuSystemPb_backlight_init_zero          {false, 0, false, 0, false, 0, false, 0}
#define McuSystemPb_screen_rotation_init_zero    {false, 0}
#define McuSystemPb_conan_flag_t_init_zero       {false, 0}
#define McuSystemPb_brightness_adapt_init_zero   {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define McuSystemPb_motor_cali_rsp_t_f0Param_tag 1
#define McuSystemPb_motor_cali_rsp_t_caliF0_tag  2
#define McuSystemPb_motor_cali_rsp_t_caliOsc_tag 3
#define McuSystemPb_band_language_t_language_tag 1
#define McuSystemPb_band_language_t_phoneMac_tag 2
#define McuSystemPb_band_language_t_needUpdateWeather_tag 3
#define McuSystemPb_oobe_notify_t_oobeStatus_tag 1
#define McuSystemPb_oobe_notify_t_phoneMac_tag   2
#define McuSystemPb_oobe_notify_t_needUpdateWeather_tag 3
#define McuSystemPb_mcu_status_status_tag        1
#define McuSystemPb_enable_mcu_status_enable_tag 1
#define McuSystemPb_boot_notify_type_tag         1
#define McuSystemPb_boot_notify_oobe_tag         2
#define McuSystemPb_boot_notify_sysTime_tag      3
#define McuSystemPb_reboot_reason_reason_tag     1
#define McuSystemPb_reboot_reason_mcuSysTime_tag 2
#define McuSystemPb_reboot_reason_eStatus_tag    3
#define McuSystemPb_backlight_c0_tag             1
#define McuSystemPb_backlight_c1_tag             2
#define McuSystemPb_backlight_time_tag           3
#define McuSystemPb_backlight_gain_tag           4
#define McuSystemPb_screen_rotation_rotation_tag 1
#define McuSystemPb_conan_flag_t_data_tag        1
#define McuSystemPb_brightness_adapt_brightness_tag 1
#define McuSystemPb_brightness_adapt_lux_tag     2

/* Struct field encoding specification for nanopb */
#define McuSystemPb_motor_cali_rsp_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   f0Param,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   caliF0,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   caliOsc,           3)
#define McuSystemPb_motor_cali_rsp_t_CALLBACK NULL
#define McuSystemPb_motor_cali_rsp_t_DEFAULT NULL

#define McuSystemPb_band_language_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   language,          1) \
X(a, CALLBACK, OPTIONAL, STRING,   phoneMac,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   needUpdateWeather,   3)
#define McuSystemPb_band_language_t_CALLBACK pb_default_field_callback
#define McuSystemPb_band_language_t_DEFAULT NULL

#define McuSystemPb_oobe_notify_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   oobeStatus,        1) \
X(a, CALLBACK, OPTIONAL, STRING,   phoneMac,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   needUpdateWeather,   3)
#define McuSystemPb_oobe_notify_t_CALLBACK pb_default_field_callback
#define McuSystemPb_oobe_notify_t_DEFAULT NULL

#define McuSystemPb_mcu_status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   status,            1)
#define McuSystemPb_mcu_status_CALLBACK NULL
#define McuSystemPb_mcu_status_DEFAULT NULL

#define McuSystemPb_enable_mcu_status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   enable,            1)
#define McuSystemPb_enable_mcu_status_CALLBACK NULL
#define McuSystemPb_enable_mcu_status_DEFAULT NULL

#define McuSystemPb_boot_notify_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  oobe,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sysTime,           3)
#define McuSystemPb_boot_notify_CALLBACK NULL
#define McuSystemPb_boot_notify_DEFAULT NULL
#define McuSystemPb_boot_notify_oobe_MSGTYPE McuSystemPb_oobe_notify_t
#define McuSystemPb_boot_notify_sysTime_MSGTYPE SystemTime_rsp_read_sys_time_t

#define McuSystemPb_reboot_reason_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   reason,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mcuSysTime,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   eStatus,           3)
#define McuSystemPb_reboot_reason_CALLBACK NULL
#define McuSystemPb_reboot_reason_DEFAULT NULL
#define McuSystemPb_reboot_reason_mcuSysTime_MSGTYPE SystemTime_rsp_read_sys_time_t

#define McuSystemPb_backlight_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    c0,                1) \
X(a, STATIC,   OPTIONAL, FLOAT,    c1,                2) \
X(a, STATIC,   OPTIONAL, FLOAT,    time,              3) \
X(a, STATIC,   OPTIONAL, FLOAT,    gain,              4)
#define McuSystemPb_backlight_CALLBACK NULL
#define McuSystemPb_backlight_DEFAULT NULL

#define McuSystemPb_screen_rotation_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   rotation,          1)
#define McuSystemPb_screen_rotation_CALLBACK NULL
#define McuSystemPb_screen_rotation_DEFAULT NULL

#define McuSystemPb_conan_flag_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   data,              1)
#define McuSystemPb_conan_flag_t_CALLBACK NULL
#define McuSystemPb_conan_flag_t_DEFAULT NULL

#define McuSystemPb_brightness_adapt_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   brightness,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   lux,               2)
#define McuSystemPb_brightness_adapt_CALLBACK NULL
#define McuSystemPb_brightness_adapt_DEFAULT NULL

extern const pb_msgdesc_t McuSystemPb_motor_cali_rsp_t_msg;
extern const pb_msgdesc_t McuSystemPb_band_language_t_msg;
extern const pb_msgdesc_t McuSystemPb_oobe_notify_t_msg;
extern const pb_msgdesc_t McuSystemPb_mcu_status_msg;
extern const pb_msgdesc_t McuSystemPb_enable_mcu_status_msg;
extern const pb_msgdesc_t McuSystemPb_boot_notify_msg;
extern const pb_msgdesc_t McuSystemPb_reboot_reason_msg;
extern const pb_msgdesc_t McuSystemPb_backlight_msg;
extern const pb_msgdesc_t McuSystemPb_screen_rotation_msg;
extern const pb_msgdesc_t McuSystemPb_conan_flag_t_msg;
extern const pb_msgdesc_t McuSystemPb_brightness_adapt_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define McuSystemPb_motor_cali_rsp_t_fields &McuSystemPb_motor_cali_rsp_t_msg
#define McuSystemPb_band_language_t_fields &McuSystemPb_band_language_t_msg
#define McuSystemPb_oobe_notify_t_fields &McuSystemPb_oobe_notify_t_msg
#define McuSystemPb_mcu_status_fields &McuSystemPb_mcu_status_msg
#define McuSystemPb_enable_mcu_status_fields &McuSystemPb_enable_mcu_status_msg
#define McuSystemPb_boot_notify_fields &McuSystemPb_boot_notify_msg
#define McuSystemPb_reboot_reason_fields &McuSystemPb_reboot_reason_msg
#define McuSystemPb_backlight_fields &McuSystemPb_backlight_msg
#define McuSystemPb_screen_rotation_fields &McuSystemPb_screen_rotation_msg
#define McuSystemPb_conan_flag_t_fields &McuSystemPb_conan_flag_t_msg
#define McuSystemPb_brightness_adapt_fields &McuSystemPb_brightness_adapt_msg

/* Maximum encoded size of messages (where known) */
/* McuSystemPb_band_language_t_size depends on runtime parameters */
/* McuSystemPb_oobe_notify_t_size depends on runtime parameters */
/* McuSystemPb_boot_notify_size depends on runtime parameters */
#define MCUSYSTEMPB_MCUSYSTEMPB_PB_H_MAX_SIZE    McuSystemPb_reboot_reason_size
#define McuSystemPb_backlight_size               20
#define McuSystemPb_brightness_adapt_size        12
#define McuSystemPb_conan_flag_t_size            11
#define McuSystemPb_enable_mcu_status_size       6
#define McuSystemPb_mcu_status_size              6
#define McuSystemPb_motor_cali_rsp_t_size        18
#define McuSystemPb_reboot_reason_size           38
#define McuSystemPb_screen_rotation_size         6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
