/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "PreferenceProvider.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PreferenceProvider_OppoSedentaryParamsT, PreferenceProvider_OppoSedentaryParamsT, AUTO)


PB_BIND(PreferenceProvider_OppoUserProfileParamT, PreferenceProvider_OppoUserProfileParamT, AUTO)


PB_BIND(PreferenceProvider_OppoActivityStepAimParamT, PreferenceProvider_OppoActivityStepAimParamT, AUTO)


PB_BIND(PreferenceProvider_OppoActivityCalorieAimParamT, PreferenceProvider_OppoActivityCalorieAimParamT, AUTO)


PB_BIND(PreferenceProvider_OppoMcuModeT, PreferenceProvider_OppoMcuModeT, AUTO)


PB_BIND(PreferenceProvider_OppoMcuWorkModeResponseT, PreferenceProvider_OppoMcuWorkModeResponseT, AUTO)


PB_BIND(PreferenceProvider_OppoTimeProfileParamT, PreferenceProvider_OppoTimeProfileParamT, AUTO)


PB_BIND(PreferenceProvider_SWITCH_T, PreferenceProvider_SWITCH_T, AUTO)


PB_BIND(PreferenceProvider_OppoSetSwitchCmdT, PreferenceProvider_OppoSetSwitchCmdT, AUTO)


PB_BIND(PreferenceProvider_PreferenceBody, PreferenceProvider_PreferenceBody, AUTO)


PB_BIND(PreferenceProvider_OppoSportsDetectParamsT, PreferenceProvider_OppoSportsDetectParamsT, AUTO)


PB_BIND(PreferenceProvider_PhoneAirPressureT, PreferenceProvider_PhoneAirPressureT, AUTO)


PB_BIND(PreferenceProvider_OppoSportsAutopauseParamsT, PreferenceProvider_OppoSportsAutopauseParamsT, AUTO)


PB_BIND(PreferenceProvider_SyncTimestampT, PreferenceProvider_SyncTimestampT, AUTO)


PB_BIND(PreferenceProvider_SportHeartrateWarnDataT, PreferenceProvider_SportHeartrateWarnDataT, AUTO)


PB_BIND(PreferenceProvider_GpsParamsT, PreferenceProvider_GpsParamsT, AUTO)


PB_BIND(PreferenceProvider_ScreenStatusT, PreferenceProvider_ScreenStatusT, AUTO)


PB_BIND(PreferenceProvider_ChargeStatusT, PreferenceProvider_ChargeStatusT, AUTO)


PB_BIND(PreferenceProvider_McuVersion, PreferenceProvider_McuVersion, AUTO)


PB_BIND(PreferenceProvider_OWSwitch, PreferenceProvider_OWSwitch, AUTO)


PB_BIND(PreferenceProvider_OWStatus, PreferenceProvider_OWStatus, AUTO)


PB_BIND(PreferenceProvider_RequestOWSwitchStatus, PreferenceProvider_RequestOWSwitchStatus, AUTO)


PB_BIND(PreferenceProvider_ResponseOWSwitchStatus, PreferenceProvider_ResponseOWSwitchStatus, AUTO)


PB_BIND(PreferenceProvider_RequestOWStatus, PreferenceProvider_RequestOWStatus, AUTO)


PB_BIND(PreferenceProvider_Msm2500StatusT, PreferenceProvider_Msm2500StatusT, AUTO)


PB_BIND(PreferenceProvider_CmdStaticHrWarnT, PreferenceProvider_CmdStaticHrWarnT, AUTO)


PB_BIND(PreferenceProvider_BatteryInfo, PreferenceProvider_BatteryInfo, AUTO)


PB_BIND(PreferenceProvider_OppoGpsDataCmdT, PreferenceProvider_OppoGpsDataCmdT, AUTO)


PB_BIND(PreferenceProvider_GpsAssistedLocationSwitchT, PreferenceProvider_GpsAssistedLocationSwitchT, AUTO)


PB_BIND(PreferenceProvider_GpsRefLocationT, PreferenceProvider_GpsRefLocationT, AUTO)






