/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_PREFERENCEPROVIDER_PREFERENCEPROVIDER_PB_H_INCLUDED
#define PB_PREFERENCEPROVIDER_PREFERENCEPROVIDER_PB_H_INCLUDED
#include <pb.h>
#include "SystemTime.pb.h"
#include "McuSystemPb.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Enum definitions */
typedef enum _PreferenceProvider_McuRebootRst {
    PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_DEBUG = 0,
    PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_EXTPIN = 1,
    PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_FAULT = 2,
    PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_OTHERS = 3
} PreferenceProvider_McuRebootRst;

typedef enum _PreferenceProvider_OppoCmd {
    PreferenceProvider_OppoCmd_OPPO_CMD_START_ZERO = 0,
    PreferenceProvider_OppoCmd_OPPO_CMD_OFF_WRIST_SWITCH = 1,
    PreferenceProvider_OppoCmd_OPPO_CMD_LIFT_WRIST_SWITCH = 2,
    PreferenceProvider_OppoCmd_OPPO_CMD_ACTIVITY_PROFILE = 3,
    PreferenceProvider_OppoCmd_OPPO_CMD_HEARTRATE_HISCTRL_SWITCH = 4,
    PreferenceProvider_OppoCmd_OPPO_CMD_STEP_AUTOUPLOAD = 5,
    PreferenceProvider_OppoCmd_OPPO_CMD_GET_MCU_VERSION = 6,
    PreferenceProvider_OppoCmd_OPPO_CMD_SET_SWITCH_CMD = 7,
    PreferenceProvider_OppoCmd_OPPO_CMD_SCREEN_STATUS = 8,
    PreferenceProvider_OppoCmd_OPPO_CMD_CHARGE_STATUS = 9,
    PreferenceProvider_OppoCmd_OPPO_CMD_SPORT_HR_WARN = 10,
    PreferenceProvider_OppoCmd_OPPO_CMD_GPS_CMD = 11,
    PreferenceProvider_OppoCmd_OPPO_CMD_WRITE_BLE_ADDR = 12,
    PreferenceProvider_OppoCmd_OPPO_CMD_ACTIVITY_CAL_PROFILE = 13,
    PreferenceProvider_OppoCmd_OPPO_CMD_MCU_MODE = 14,
    PreferenceProvider_OppoCmd_OPPO_CMD_STATIC_HR_WARN = 15,
    PreferenceProvider_OppoCmd_OPPO_CMD_MSM2500_STATUS = 16,
    PreferenceProvider_OppoCmd_OPPO_CMD_BATTERY_INFO = 17,
    PreferenceProvider_OppoCmd_OPPO_CMD_GPS_DATA = 18,
    PreferenceProvider_OppoCmd_OPPO_CMD_SPORTS_DETECT = 19,
    PreferenceProvider_OppoCmd_OPPO_CMD_SPORTS_AUTOPAUSE = 20,
    PreferenceProvider_OppoCmd_OPPO_CMD_PHONE_AIR_PRESSURE = 21,
    PreferenceProvider_OppoCmd_OPPO_CMD_SYNC_TIMESTAMP = 22,
    PreferenceProvider_OppoCmd_OPPO_CMD_TEST = 101
} PreferenceProvider_OppoCmd;

typedef enum _PreferenceProvider_OppoGpsCmd {
    PreferenceProvider_OppoGpsCmd_OPPO_GPS_CMD_NULL = 0,
    PreferenceProvider_OppoGpsCmd_OPPO_GPS_CMD_LOCATION = 1,
    PreferenceProvider_OppoGpsCmd_OPPO_GPS_CMD_AGPS_LOCATION_SWITCH = 2
} PreferenceProvider_OppoGpsCmd;

/* Struct definitions */
/* Message definitions */
typedef struct _PreferenceProvider_OppoSedentaryParamsT {
    uint32_t sw;
    uint32_t startTime;
    uint32_t endTime;
    uint32_t exclude;
} PreferenceProvider_OppoSedentaryParamsT;

typedef struct _PreferenceProvider_OppoUserProfileParamT {
    uint32_t weight;
    uint32_t height;
    uint32_t age;
    uint32_t sex;
} PreferenceProvider_OppoUserProfileParamT;

typedef struct _PreferenceProvider_OppoActivityStepAimParamT {
    uint32_t stepAim;
} PreferenceProvider_OppoActivityStepAimParamT;

typedef struct _PreferenceProvider_OppoActivityCalorieAimParamT {
    uint32_t calorieAim;
} PreferenceProvider_OppoActivityCalorieAimParamT;

typedef struct _PreferenceProvider_OppoMcuModeT {
    uint32_t mode;
    bool has_sysTime;
    SystemTime_req_update_sys_time_t sysTime;
    uint32_t type;
} PreferenceProvider_OppoMcuModeT;

typedef struct _PreferenceProvider_OppoMcuWorkModeResponseT {
    uint32_t mode;
    bool has_lightCali;
    McuSystemPb_light_cali_rsp_t lightCali;
    uint32_t lastMode;
    bool has_mcuSysTime;
    SystemTime_rsp_read_sys_time_t mcuSysTime;
    int32_t rebootReason;
    uint32_t type;
} PreferenceProvider_OppoMcuWorkModeResponseT;

typedef struct _PreferenceProvider_OppoTimeProfileParamT {
    pb_size_t which_data;
    union {
        SystemTime_req_update_gmt_time_t gmt;
        SystemTime_req_update_sys_time_t sys;
        SystemTime_req_read_sys_time_t read;
    } data;
} PreferenceProvider_OppoTimeProfileParamT;

typedef struct _PreferenceProvider_SWITCH_T {
    uint32_t sw;
} PreferenceProvider_SWITCH_T;

typedef struct _PreferenceProvider_OppoSetSwitchCmdT {
    int32_t cmd;
    pb_size_t which_payload;
    union {
        PreferenceProvider_SWITCH_T offwristSw;
        PreferenceProvider_SWITCH_T liftwristSw;
        PreferenceProvider_SWITCH_T backlightSw;
        PreferenceProvider_SWITCH_T hisctrlSw;
        PreferenceProvider_SWITCH_T workmodeSw;
    } payload;
} PreferenceProvider_OppoSetSwitchCmdT;

typedef struct _PreferenceProvider_OppoSportsDetectParamsT {
    uint32_t sw;
    uint32_t continuousTime;
} PreferenceProvider_OppoSportsDetectParamsT;

typedef struct _PreferenceProvider_PhoneAirPressureT {
    int32_t errCode;
    float pressureVal;
} PreferenceProvider_PhoneAirPressureT;

typedef struct _PreferenceProvider_OppoSportsAutopauseParamsT {
    uint32_t sw;
    uint32_t reserve;
} PreferenceProvider_OppoSportsAutopauseParamsT;

typedef struct _PreferenceProvider_SyncTimestampT {
    int64_t hostTimestamp;
} PreferenceProvider_SyncTimestampT;

typedef struct _PreferenceProvider_SportHeartrateWarnDataT {
    uint32_t sportHrWarnEnable;
    uint32_t sportHrWarnValue;
} PreferenceProvider_SportHeartrateWarnDataT;

typedef struct _PreferenceProvider_GpsParamsT {
    pb_callback_t str;
} PreferenceProvider_GpsParamsT;

typedef struct _PreferenceProvider_ScreenStatusT {
    uint32_t screenStatus;
} PreferenceProvider_ScreenStatusT;

typedef struct _PreferenceProvider_ChargeStatusT {
    uint32_t chargeStatus;
} PreferenceProvider_ChargeStatusT;

typedef struct _PreferenceProvider_McuVersion {
    pb_callback_t romVersion;
    pb_callback_t hardwareVersion;
    pb_callback_t algoVersion;
    uint32_t bn;
} PreferenceProvider_McuVersion;

typedef struct _PreferenceProvider_OWSwitch {
    uint32_t sw;
} PreferenceProvider_OWSwitch;

typedef struct _PreferenceProvider_OWStatus {
    bool has_status;
    uint32_t status;
} PreferenceProvider_OWStatus;

typedef struct _PreferenceProvider_RequestOWSwitchStatus {
    uint32_t type;
} PreferenceProvider_RequestOWSwitchStatus;

typedef struct _PreferenceProvider_ResponseOWSwitchStatus {
    uint32_t status;
} PreferenceProvider_ResponseOWSwitchStatus;

typedef struct _PreferenceProvider_RequestOWStatus {
    uint32_t type;
} PreferenceProvider_RequestOWStatus;

typedef struct _PreferenceProvider_Msm2500StatusT {
    uint32_t cpuStatus;
} PreferenceProvider_Msm2500StatusT;

typedef struct _PreferenceProvider_CmdStaticHrWarnT {
    uint32_t hrWarnHigh;
    uint32_t hrWarnLow;
    uint32_t hrDuration;
} PreferenceProvider_CmdStaticHrWarnT;

typedef struct _PreferenceProvider_BatteryInfo {
    uint32_t voltage;
    uint32_t capacity;
} PreferenceProvider_BatteryInfo;

typedef struct _PreferenceProvider_GpsAssistedLocationSwitchT {
    uint32_t assistedSwitchStatus;
} PreferenceProvider_GpsAssistedLocationSwitchT;

typedef struct _PreferenceProvider_GpsRefLocationT {
    uint32_t gpsRefUtc;
    int32_t gpsRefLat;
    int32_t gpsRefLon;
    int32_t gpsRefAltitude;
} PreferenceProvider_GpsRefLocationT;

typedef struct _PreferenceProvider_OppoGpsDataCmdT {
    int32_t cmd;
    pb_size_t which_payload;
    union {
        PreferenceProvider_GpsRefLocationT gpsLocInfo;
        PreferenceProvider_GpsAssistedLocationSwitchT agpsLocSwitch;
    } payload;
} PreferenceProvider_OppoGpsDataCmdT;

typedef struct _PreferenceProvider_PreferenceBody {
    int32_t cmd;
    pb_size_t which_payload;
    union {
        PreferenceProvider_OppoUserProfileParamT userprofile;
        PreferenceProvider_OppoSedentaryParamsT sedentary;
        PreferenceProvider_OppoActivityStepAimParamT step;
        PreferenceProvider_OppoTimeProfileParamT gmttime;
        PreferenceProvider_OppoSetSwitchCmdT sw;
        PreferenceProvider_SportHeartrateWarnDataT hr;
        PreferenceProvider_GpsParamsT mode;
        PreferenceProvider_ScreenStatusT sreenStatus;
        PreferenceProvider_ChargeStatusT chargeStatus;
        PreferenceProvider_OppoActivityCalorieAimParamT cal;
        PreferenceProvider_OppoMcuModeT workmode;
        PreferenceProvider_CmdStaticHrWarnT cmdHrWarn;
        PreferenceProvider_Msm2500StatusT cpuStatus;
        PreferenceProvider_BatteryInfo batteryInfo;
        PreferenceProvider_OppoGpsDataCmdT gpsData;
        PreferenceProvider_OppoSportsDetectParamsT params;
        PreferenceProvider_OppoSportsAutopauseParamsT autopauseParams;
        PreferenceProvider_PhoneAirPressureT pressureVal;
        PreferenceProvider_SyncTimestampT timestamp;
    } payload;
} PreferenceProvider_PreferenceBody;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _PreferenceProvider_McuRebootRst_MIN PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_DEBUG
#define _PreferenceProvider_McuRebootRst_MAX PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_OTHERS
#define _PreferenceProvider_McuRebootRst_ARRAYSIZE ((PreferenceProvider_McuRebootRst)(PreferenceProvider_McuRebootRst_MCU_REBOOT_RST_OTHERS+1))

#define _PreferenceProvider_OppoCmd_MIN PreferenceProvider_OppoCmd_OPPO_CMD_START_ZERO
#define _PreferenceProvider_OppoCmd_MAX PreferenceProvider_OppoCmd_OPPO_CMD_TEST
#define _PreferenceProvider_OppoCmd_ARRAYSIZE ((PreferenceProvider_OppoCmd)(PreferenceProvider_OppoCmd_OPPO_CMD_TEST+1))

#define _PreferenceProvider_OppoGpsCmd_MIN PreferenceProvider_OppoGpsCmd_OPPO_GPS_CMD_NULL
#define _PreferenceProvider_OppoGpsCmd_MAX PreferenceProvider_OppoGpsCmd_OPPO_GPS_CMD_AGPS_LOCATION_SWITCH
#define _PreferenceProvider_OppoGpsCmd_ARRAYSIZE ((PreferenceProvider_OppoGpsCmd)(PreferenceProvider_OppoGpsCmd_OPPO_GPS_CMD_AGPS_LOCATION_SWITCH+1))
































/* Initializer values for message structs */
#define PreferenceProvider_OppoSedentaryParamsT_init_default {0, 0, 0, 0}
#define PreferenceProvider_OppoUserProfileParamT_init_default {0, 0, 0, 0}
#define PreferenceProvider_OppoActivityStepAimParamT_init_default {0}
#define PreferenceProvider_OppoActivityCalorieAimParamT_init_default {0}
#define PreferenceProvider_OppoMcuModeT_init_default {0, false, SystemTime_req_update_sys_time_t_init_default, 0}
#define PreferenceProvider_OppoMcuWorkModeResponseT_init_default {0, false, McuSystemPb_light_cali_rsp_t_init_default, 0, false, SystemTime_rsp_read_sys_time_t_init_default, 0, 0}
#define PreferenceProvider_OppoTimeProfileParamT_init_default {0, {SystemTime_req_update_gmt_time_t_init_default}}
#define PreferenceProvider_SWITCH_T_init_default {0}
#define PreferenceProvider_OppoSetSwitchCmdT_init_default {0, 0, {PreferenceProvider_SWITCH_T_init_default}}
#define PreferenceProvider_PreferenceBody_init_default {0, 0, {PreferenceProvider_OppoUserProfileParamT_init_default}}
#define PreferenceProvider_OppoSportsDetectParamsT_init_default {0, 0}
#define PreferenceProvider_PhoneAirPressureT_init_default {0, 0}
#define PreferenceProvider_OppoSportsAutopauseParamsT_init_default {0, 0}
#define PreferenceProvider_SyncTimestampT_init_default {0}
#define PreferenceProvider_SportHeartrateWarnDataT_init_default {0, 0}
#define PreferenceProvider_GpsParamsT_init_default {{{NULL}, NULL}}
#define PreferenceProvider_ScreenStatusT_init_default {0}
#define PreferenceProvider_ChargeStatusT_init_default {0}
#define PreferenceProvider_McuVersion_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define PreferenceProvider_OWSwitch_init_default {0}
#define PreferenceProvider_OWStatus_init_default {false, 0}
#define PreferenceProvider_RequestOWSwitchStatus_init_default {0}
#define PreferenceProvider_ResponseOWSwitchStatus_init_default {0}
#define PreferenceProvider_RequestOWStatus_init_default {0}
#define PreferenceProvider_Msm2500StatusT_init_default {0}
#define PreferenceProvider_CmdStaticHrWarnT_init_default {0, 0, 0}
#define PreferenceProvider_BatteryInfo_init_default {0, 0}
#define PreferenceProvider_OppoGpsDataCmdT_init_default {0, 0, {PreferenceProvider_GpsRefLocationT_init_default}}
#define PreferenceProvider_GpsAssistedLocationSwitchT_init_default {0}
#define PreferenceProvider_GpsRefLocationT_init_default {0, 0, 0, 0}
#define PreferenceProvider_OppoSedentaryParamsT_init_zero {0, 0, 0, 0}
#define PreferenceProvider_OppoUserProfileParamT_init_zero {0, 0, 0, 0}
#define PreferenceProvider_OppoActivityStepAimParamT_init_zero {0}
#define PreferenceProvider_OppoActivityCalorieAimParamT_init_zero {0}
#define PreferenceProvider_OppoMcuModeT_init_zero {0, false, SystemTime_req_update_sys_time_t_init_zero, 0}
#define PreferenceProvider_OppoMcuWorkModeResponseT_init_zero {0, false, McuSystemPb_light_cali_rsp_t_init_zero, 0, false, SystemTime_rsp_read_sys_time_t_init_zero, 0, 0}
#define PreferenceProvider_OppoTimeProfileParamT_init_zero {0, {SystemTime_req_update_gmt_time_t_init_zero}}
#define PreferenceProvider_SWITCH_T_init_zero    {0}
#define PreferenceProvider_OppoSetSwitchCmdT_init_zero {0, 0, {PreferenceProvider_SWITCH_T_init_zero}}
#define PreferenceProvider_PreferenceBody_init_zero {0, 0, {PreferenceProvider_OppoUserProfileParamT_init_zero}}
#define PreferenceProvider_OppoSportsDetectParamsT_init_zero {0, 0}
#define PreferenceProvider_PhoneAirPressureT_init_zero {0, 0}
#define PreferenceProvider_OppoSportsAutopauseParamsT_init_zero {0, 0}
#define PreferenceProvider_SyncTimestampT_init_zero {0}
#define PreferenceProvider_SportHeartrateWarnDataT_init_zero {0, 0}
#define PreferenceProvider_GpsParamsT_init_zero  {{{NULL}, NULL}}
#define PreferenceProvider_ScreenStatusT_init_zero {0}
#define PreferenceProvider_ChargeStatusT_init_zero {0}
#define PreferenceProvider_McuVersion_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define PreferenceProvider_OWSwitch_init_zero    {0}
#define PreferenceProvider_OWStatus_init_zero    {false, 0}
#define PreferenceProvider_RequestOWSwitchStatus_init_zero {0}
#define PreferenceProvider_ResponseOWSwitchStatus_init_zero {0}
#define PreferenceProvider_RequestOWStatus_init_zero {0}
#define PreferenceProvider_Msm2500StatusT_init_zero {0}
#define PreferenceProvider_CmdStaticHrWarnT_init_zero {0, 0, 0}
#define PreferenceProvider_BatteryInfo_init_zero {0, 0}
#define PreferenceProvider_OppoGpsDataCmdT_init_zero {0, 0, {PreferenceProvider_GpsRefLocationT_init_zero}}
#define PreferenceProvider_GpsAssistedLocationSwitchT_init_zero {0}
#define PreferenceProvider_GpsRefLocationT_init_zero {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PreferenceProvider_OppoSedentaryParamsT_sw_tag 1
#define PreferenceProvider_OppoSedentaryParamsT_startTime_tag 2
#define PreferenceProvider_OppoSedentaryParamsT_endTime_tag 3
#define PreferenceProvider_OppoSedentaryParamsT_exclude_tag 4
#define PreferenceProvider_OppoUserProfileParamT_weight_tag 1
#define PreferenceProvider_OppoUserProfileParamT_height_tag 2
#define PreferenceProvider_OppoUserProfileParamT_age_tag 3
#define PreferenceProvider_OppoUserProfileParamT_sex_tag 4
#define PreferenceProvider_OppoActivityStepAimParamT_stepAim_tag 1
#define PreferenceProvider_OppoActivityCalorieAimParamT_calorieAim_tag 1
#define PreferenceProvider_OppoMcuModeT_mode_tag 1
#define PreferenceProvider_OppoMcuModeT_sysTime_tag 2
#define PreferenceProvider_OppoMcuModeT_type_tag 3
#define PreferenceProvider_OppoMcuWorkModeResponseT_mode_tag 1
#define PreferenceProvider_OppoMcuWorkModeResponseT_lightCali_tag 2
#define PreferenceProvider_OppoMcuWorkModeResponseT_lastMode_tag 3
#define PreferenceProvider_OppoMcuWorkModeResponseT_mcuSysTime_tag 4
#define PreferenceProvider_OppoMcuWorkModeResponseT_rebootReason_tag 5
#define PreferenceProvider_OppoMcuWorkModeResponseT_type_tag 6
#define PreferenceProvider_OppoTimeProfileParamT_gmt_tag 1
#define PreferenceProvider_OppoTimeProfileParamT_sys_tag 2
#define PreferenceProvider_OppoTimeProfileParamT_read_tag 3
#define PreferenceProvider_SWITCH_T_sw_tag       1
#define PreferenceProvider_OppoSetSwitchCmdT_cmd_tag 1
#define PreferenceProvider_OppoSetSwitchCmdT_offwristSw_tag 2
#define PreferenceProvider_OppoSetSwitchCmdT_liftwristSw_tag 3
#define PreferenceProvider_OppoSetSwitchCmdT_backlightSw_tag 4
#define PreferenceProvider_OppoSetSwitchCmdT_hisctrlSw_tag 5
#define PreferenceProvider_OppoSetSwitchCmdT_workmodeSw_tag 6
#define PreferenceProvider_OppoSportsDetectParamsT_sw_tag 1
#define PreferenceProvider_OppoSportsDetectParamsT_continuousTime_tag 2
#define PreferenceProvider_PhoneAirPressureT_errCode_tag 1
#define PreferenceProvider_PhoneAirPressureT_pressureVal_tag 2
#define PreferenceProvider_OppoSportsAutopauseParamsT_sw_tag 1
#define PreferenceProvider_OppoSportsAutopauseParamsT_reserve_tag 2
#define PreferenceProvider_SyncTimestampT_hostTimestamp_tag 1
#define PreferenceProvider_SportHeartrateWarnDataT_sportHrWarnEnable_tag 1
#define PreferenceProvider_SportHeartrateWarnDataT_sportHrWarnValue_tag 2
#define PreferenceProvider_GpsParamsT_str_tag    1
#define PreferenceProvider_ScreenStatusT_screenStatus_tag 1
#define PreferenceProvider_ChargeStatusT_chargeStatus_tag 1
#define PreferenceProvider_McuVersion_romVersion_tag 1
#define PreferenceProvider_McuVersion_hardwareVersion_tag 2
#define PreferenceProvider_McuVersion_algoVersion_tag 3
#define PreferenceProvider_McuVersion_bn_tag     4
#define PreferenceProvider_OWSwitch_sw_tag       1
#define PreferenceProvider_OWStatus_status_tag   1
#define PreferenceProvider_RequestOWSwitchStatus_type_tag 1
#define PreferenceProvider_ResponseOWSwitchStatus_status_tag 1
#define PreferenceProvider_RequestOWStatus_type_tag 1
#define PreferenceProvider_Msm2500StatusT_cpuStatus_tag 1
#define PreferenceProvider_CmdStaticHrWarnT_hrWarnHigh_tag 1
#define PreferenceProvider_CmdStaticHrWarnT_hrWarnLow_tag 2
#define PreferenceProvider_CmdStaticHrWarnT_hrDuration_tag 3
#define PreferenceProvider_BatteryInfo_voltage_tag 1
#define PreferenceProvider_BatteryInfo_capacity_tag 2
#define PreferenceProvider_GpsAssistedLocationSwitchT_assistedSwitchStatus_tag 1
#define PreferenceProvider_GpsRefLocationT_gpsRefUtc_tag 1
#define PreferenceProvider_GpsRefLocationT_gpsRefLat_tag 2
#define PreferenceProvider_GpsRefLocationT_gpsRefLon_tag 3
#define PreferenceProvider_GpsRefLocationT_gpsRefAltitude_tag 4
#define PreferenceProvider_OppoGpsDataCmdT_cmd_tag 1
#define PreferenceProvider_OppoGpsDataCmdT_gpsLocInfo_tag 2
#define PreferenceProvider_OppoGpsDataCmdT_agpsLocSwitch_tag 3
#define PreferenceProvider_PreferenceBody_cmd_tag 1
#define PreferenceProvider_PreferenceBody_userprofile_tag 2
#define PreferenceProvider_PreferenceBody_sedentary_tag 3
#define PreferenceProvider_PreferenceBody_step_tag 4
#define PreferenceProvider_PreferenceBody_gmttime_tag 5
#define PreferenceProvider_PreferenceBody_sw_tag 6
#define PreferenceProvider_PreferenceBody_hr_tag 7
#define PreferenceProvider_PreferenceBody_mode_tag 8
#define PreferenceProvider_PreferenceBody_sreenStatus_tag 9
#define PreferenceProvider_PreferenceBody_chargeStatus_tag 10
#define PreferenceProvider_PreferenceBody_cal_tag 11
#define PreferenceProvider_PreferenceBody_workmode_tag 12
#define PreferenceProvider_PreferenceBody_cmdHrWarn_tag 13
#define PreferenceProvider_PreferenceBody_cpuStatus_tag 14
#define PreferenceProvider_PreferenceBody_batteryInfo_tag 15
#define PreferenceProvider_PreferenceBody_gpsData_tag 16
#define PreferenceProvider_PreferenceBody_params_tag 17
#define PreferenceProvider_PreferenceBody_autopauseParams_tag 18
#define PreferenceProvider_PreferenceBody_pressureVal_tag 19
#define PreferenceProvider_PreferenceBody_timestamp_tag 20

/* Struct field encoding specification for nanopb */
#define PreferenceProvider_OppoSedentaryParamsT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sw,                1) \
X(a, STATIC,   SINGULAR, UINT32,   startTime,         2) \
X(a, STATIC,   SINGULAR, UINT32,   endTime,           3) \
X(a, STATIC,   SINGULAR, UINT32,   exclude,           4)
#define PreferenceProvider_OppoSedentaryParamsT_CALLBACK NULL
#define PreferenceProvider_OppoSedentaryParamsT_DEFAULT NULL

#define PreferenceProvider_OppoUserProfileParamT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   weight,            1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, STATIC,   SINGULAR, UINT32,   age,               3) \
X(a, STATIC,   SINGULAR, UINT32,   sex,               4)
#define PreferenceProvider_OppoUserProfileParamT_CALLBACK NULL
#define PreferenceProvider_OppoUserProfileParamT_DEFAULT NULL

#define PreferenceProvider_OppoActivityStepAimParamT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   stepAim,           1)
#define PreferenceProvider_OppoActivityStepAimParamT_CALLBACK NULL
#define PreferenceProvider_OppoActivityStepAimParamT_DEFAULT NULL

#define PreferenceProvider_OppoActivityCalorieAimParamT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   calorieAim,        1)
#define PreferenceProvider_OppoActivityCalorieAimParamT_CALLBACK NULL
#define PreferenceProvider_OppoActivityCalorieAimParamT_DEFAULT NULL

#define PreferenceProvider_OppoMcuModeT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sysTime,           2) \
X(a, STATIC,   SINGULAR, UINT32,   type,              3)
#define PreferenceProvider_OppoMcuModeT_CALLBACK NULL
#define PreferenceProvider_OppoMcuModeT_DEFAULT NULL
#define PreferenceProvider_OppoMcuModeT_sysTime_MSGTYPE SystemTime_req_update_sys_time_t

#define PreferenceProvider_OppoMcuWorkModeResponseT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  lightCali,         2) \
X(a, STATIC,   SINGULAR, UINT32,   lastMode,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mcuSysTime,        4) \
X(a, STATIC,   SINGULAR, INT32,    rebootReason,      5) \
X(a, STATIC,   SINGULAR, UINT32,   type,              6)
#define PreferenceProvider_OppoMcuWorkModeResponseT_CALLBACK NULL
#define PreferenceProvider_OppoMcuWorkModeResponseT_DEFAULT NULL
#define PreferenceProvider_OppoMcuWorkModeResponseT_lightCali_MSGTYPE McuSystemPb_light_cali_rsp_t
#define PreferenceProvider_OppoMcuWorkModeResponseT_mcuSysTime_MSGTYPE SystemTime_rsp_read_sys_time_t

#define PreferenceProvider_OppoTimeProfileParamT_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,gmt,data.gmt),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,sys,data.sys),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,read,data.read),   3)
#define PreferenceProvider_OppoTimeProfileParamT_CALLBACK NULL
#define PreferenceProvider_OppoTimeProfileParamT_DEFAULT NULL
#define PreferenceProvider_OppoTimeProfileParamT_data_gmt_MSGTYPE SystemTime_req_update_gmt_time_t
#define PreferenceProvider_OppoTimeProfileParamT_data_sys_MSGTYPE SystemTime_req_update_sys_time_t
#define PreferenceProvider_OppoTimeProfileParamT_data_read_MSGTYPE SystemTime_req_read_sys_time_t

#define PreferenceProvider_SWITCH_T_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sw,                1)
#define PreferenceProvider_SWITCH_T_CALLBACK NULL
#define PreferenceProvider_SWITCH_T_DEFAULT NULL

#define PreferenceProvider_OppoSetSwitchCmdT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    cmd,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,offwristSw,payload.offwristSw),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,liftwristSw,payload.liftwristSw),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,backlightSw,payload.backlightSw),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hisctrlSw,payload.hisctrlSw),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,workmodeSw,payload.workmodeSw),   6)
#define PreferenceProvider_OppoSetSwitchCmdT_CALLBACK NULL
#define PreferenceProvider_OppoSetSwitchCmdT_DEFAULT NULL
#define PreferenceProvider_OppoSetSwitchCmdT_payload_offwristSw_MSGTYPE PreferenceProvider_SWITCH_T
#define PreferenceProvider_OppoSetSwitchCmdT_payload_liftwristSw_MSGTYPE PreferenceProvider_SWITCH_T
#define PreferenceProvider_OppoSetSwitchCmdT_payload_backlightSw_MSGTYPE PreferenceProvider_SWITCH_T
#define PreferenceProvider_OppoSetSwitchCmdT_payload_hisctrlSw_MSGTYPE PreferenceProvider_SWITCH_T
#define PreferenceProvider_OppoSetSwitchCmdT_payload_workmodeSw_MSGTYPE PreferenceProvider_SWITCH_T

#define PreferenceProvider_PreferenceBody_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    cmd,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,userprofile,payload.userprofile),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sedentary,payload.sedentary),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,step,payload.step),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gmttime,payload.gmttime),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sw,payload.sw),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,hr,payload.hr),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mode,payload.mode),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sreenStatus,payload.sreenStatus),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,chargeStatus,payload.chargeStatus),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cal,payload.cal),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,workmode,payload.workmode),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cmdHrWarn,payload.cmdHrWarn),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cpuStatus,payload.cpuStatus),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,batteryInfo,payload.batteryInfo),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpsData,payload.gpsData),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,params,payload.params),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,autopauseParams,payload.autopauseParams),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,pressureVal,payload.pressureVal),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,timestamp,payload.timestamp),  20)
#define PreferenceProvider_PreferenceBody_CALLBACK NULL
#define PreferenceProvider_PreferenceBody_DEFAULT NULL
#define PreferenceProvider_PreferenceBody_payload_userprofile_MSGTYPE PreferenceProvider_OppoUserProfileParamT
#define PreferenceProvider_PreferenceBody_payload_sedentary_MSGTYPE PreferenceProvider_OppoSedentaryParamsT
#define PreferenceProvider_PreferenceBody_payload_step_MSGTYPE PreferenceProvider_OppoActivityStepAimParamT
#define PreferenceProvider_PreferenceBody_payload_gmttime_MSGTYPE PreferenceProvider_OppoTimeProfileParamT
#define PreferenceProvider_PreferenceBody_payload_sw_MSGTYPE PreferenceProvider_OppoSetSwitchCmdT
#define PreferenceProvider_PreferenceBody_payload_hr_MSGTYPE PreferenceProvider_SportHeartrateWarnDataT
#define PreferenceProvider_PreferenceBody_payload_mode_MSGTYPE PreferenceProvider_GpsParamsT
#define PreferenceProvider_PreferenceBody_payload_sreenStatus_MSGTYPE PreferenceProvider_ScreenStatusT
#define PreferenceProvider_PreferenceBody_payload_chargeStatus_MSGTYPE PreferenceProvider_ChargeStatusT
#define PreferenceProvider_PreferenceBody_payload_cal_MSGTYPE PreferenceProvider_OppoActivityCalorieAimParamT
#define PreferenceProvider_PreferenceBody_payload_workmode_MSGTYPE PreferenceProvider_OppoMcuModeT
#define PreferenceProvider_PreferenceBody_payload_cmdHrWarn_MSGTYPE PreferenceProvider_CmdStaticHrWarnT
#define PreferenceProvider_PreferenceBody_payload_cpuStatus_MSGTYPE PreferenceProvider_Msm2500StatusT
#define PreferenceProvider_PreferenceBody_payload_batteryInfo_MSGTYPE PreferenceProvider_BatteryInfo
#define PreferenceProvider_PreferenceBody_payload_gpsData_MSGTYPE PreferenceProvider_OppoGpsDataCmdT
#define PreferenceProvider_PreferenceBody_payload_params_MSGTYPE PreferenceProvider_OppoSportsDetectParamsT
#define PreferenceProvider_PreferenceBody_payload_autopauseParams_MSGTYPE PreferenceProvider_OppoSportsAutopauseParamsT
#define PreferenceProvider_PreferenceBody_payload_pressureVal_MSGTYPE PreferenceProvider_PhoneAirPressureT
#define PreferenceProvider_PreferenceBody_payload_timestamp_MSGTYPE PreferenceProvider_SyncTimestampT

#define PreferenceProvider_OppoSportsDetectParamsT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sw,                1) \
X(a, STATIC,   SINGULAR, UINT32,   continuousTime,    2)
#define PreferenceProvider_OppoSportsDetectParamsT_CALLBACK NULL
#define PreferenceProvider_OppoSportsDetectParamsT_DEFAULT NULL

#define PreferenceProvider_PhoneAirPressureT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    errCode,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    pressureVal,       2)
#define PreferenceProvider_PhoneAirPressureT_CALLBACK NULL
#define PreferenceProvider_PhoneAirPressureT_DEFAULT NULL

#define PreferenceProvider_OppoSportsAutopauseParamsT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sw,                1) \
X(a, STATIC,   SINGULAR, UINT32,   reserve,           2)
#define PreferenceProvider_OppoSportsAutopauseParamsT_CALLBACK NULL
#define PreferenceProvider_OppoSportsAutopauseParamsT_DEFAULT NULL

#define PreferenceProvider_SyncTimestampT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SFIXED64, hostTimestamp,     1)
#define PreferenceProvider_SyncTimestampT_CALLBACK NULL
#define PreferenceProvider_SyncTimestampT_DEFAULT NULL

#define PreferenceProvider_SportHeartrateWarnDataT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sportHrWarnEnable,   1) \
X(a, STATIC,   SINGULAR, UINT32,   sportHrWarnValue,   2)
#define PreferenceProvider_SportHeartrateWarnDataT_CALLBACK NULL
#define PreferenceProvider_SportHeartrateWarnDataT_DEFAULT NULL

#define PreferenceProvider_GpsParamsT_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   str,               1)
#define PreferenceProvider_GpsParamsT_CALLBACK pb_default_field_callback
#define PreferenceProvider_GpsParamsT_DEFAULT NULL

#define PreferenceProvider_ScreenStatusT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   screenStatus,      1)
#define PreferenceProvider_ScreenStatusT_CALLBACK NULL
#define PreferenceProvider_ScreenStatusT_DEFAULT NULL

#define PreferenceProvider_ChargeStatusT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chargeStatus,      1)
#define PreferenceProvider_ChargeStatusT_CALLBACK NULL
#define PreferenceProvider_ChargeStatusT_DEFAULT NULL

#define PreferenceProvider_McuVersion_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    romVersion,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    hardwareVersion,   2) \
X(a, CALLBACK, SINGULAR, BYTES,    algoVersion,       3) \
X(a, STATIC,   SINGULAR, UINT32,   bn,                4)
#define PreferenceProvider_McuVersion_CALLBACK pb_default_field_callback
#define PreferenceProvider_McuVersion_DEFAULT NULL

#define PreferenceProvider_OWSwitch_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sw,                1)
#define PreferenceProvider_OWSwitch_CALLBACK NULL
#define PreferenceProvider_OWSwitch_DEFAULT NULL

#define PreferenceProvider_OWStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   status,            1)
#define PreferenceProvider_OWStatus_CALLBACK NULL
#define PreferenceProvider_OWStatus_DEFAULT NULL

#define PreferenceProvider_RequestOWSwitchStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1)
#define PreferenceProvider_RequestOWSwitchStatus_CALLBACK NULL
#define PreferenceProvider_RequestOWSwitchStatus_DEFAULT NULL

#define PreferenceProvider_ResponseOWSwitchStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1)
#define PreferenceProvider_ResponseOWSwitchStatus_CALLBACK NULL
#define PreferenceProvider_ResponseOWSwitchStatus_DEFAULT NULL

#define PreferenceProvider_RequestOWStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1)
#define PreferenceProvider_RequestOWStatus_CALLBACK NULL
#define PreferenceProvider_RequestOWStatus_DEFAULT NULL

#define PreferenceProvider_Msm2500StatusT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cpuStatus,         1)
#define PreferenceProvider_Msm2500StatusT_CALLBACK NULL
#define PreferenceProvider_Msm2500StatusT_DEFAULT NULL

#define PreferenceProvider_CmdStaticHrWarnT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hrWarnHigh,        1) \
X(a, STATIC,   SINGULAR, UINT32,   hrWarnLow,         2) \
X(a, STATIC,   SINGULAR, UINT32,   hrDuration,        3)
#define PreferenceProvider_CmdStaticHrWarnT_CALLBACK NULL
#define PreferenceProvider_CmdStaticHrWarnT_DEFAULT NULL

#define PreferenceProvider_BatteryInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           1) \
X(a, STATIC,   SINGULAR, UINT32,   capacity,          2)
#define PreferenceProvider_BatteryInfo_CALLBACK NULL
#define PreferenceProvider_BatteryInfo_DEFAULT NULL

#define PreferenceProvider_OppoGpsDataCmdT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    cmd,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gpsLocInfo,payload.gpsLocInfo),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,agpsLocSwitch,payload.agpsLocSwitch),   3)
#define PreferenceProvider_OppoGpsDataCmdT_CALLBACK NULL
#define PreferenceProvider_OppoGpsDataCmdT_DEFAULT NULL
#define PreferenceProvider_OppoGpsDataCmdT_payload_gpsLocInfo_MSGTYPE PreferenceProvider_GpsRefLocationT
#define PreferenceProvider_OppoGpsDataCmdT_payload_agpsLocSwitch_MSGTYPE PreferenceProvider_GpsAssistedLocationSwitchT

#define PreferenceProvider_GpsAssistedLocationSwitchT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   assistedSwitchStatus,   1)
#define PreferenceProvider_GpsAssistedLocationSwitchT_CALLBACK NULL
#define PreferenceProvider_GpsAssistedLocationSwitchT_DEFAULT NULL

#define PreferenceProvider_GpsRefLocationT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gpsRefUtc,         1) \
X(a, STATIC,   SINGULAR, SINT32,   gpsRefLat,         2) \
X(a, STATIC,   SINGULAR, SINT32,   gpsRefLon,         3) \
X(a, STATIC,   SINGULAR, SINT32,   gpsRefAltitude,    4)
#define PreferenceProvider_GpsRefLocationT_CALLBACK NULL
#define PreferenceProvider_GpsRefLocationT_DEFAULT NULL

extern const pb_msgdesc_t PreferenceProvider_OppoSedentaryParamsT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoUserProfileParamT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoActivityStepAimParamT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoActivityCalorieAimParamT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoMcuModeT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoMcuWorkModeResponseT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoTimeProfileParamT_msg;
extern const pb_msgdesc_t PreferenceProvider_SWITCH_T_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoSetSwitchCmdT_msg;
extern const pb_msgdesc_t PreferenceProvider_PreferenceBody_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoSportsDetectParamsT_msg;
extern const pb_msgdesc_t PreferenceProvider_PhoneAirPressureT_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoSportsAutopauseParamsT_msg;
extern const pb_msgdesc_t PreferenceProvider_SyncTimestampT_msg;
extern const pb_msgdesc_t PreferenceProvider_SportHeartrateWarnDataT_msg;
extern const pb_msgdesc_t PreferenceProvider_GpsParamsT_msg;
extern const pb_msgdesc_t PreferenceProvider_ScreenStatusT_msg;
extern const pb_msgdesc_t PreferenceProvider_ChargeStatusT_msg;
extern const pb_msgdesc_t PreferenceProvider_McuVersion_msg;
extern const pb_msgdesc_t PreferenceProvider_OWSwitch_msg;
extern const pb_msgdesc_t PreferenceProvider_OWStatus_msg;
extern const pb_msgdesc_t PreferenceProvider_RequestOWSwitchStatus_msg;
extern const pb_msgdesc_t PreferenceProvider_ResponseOWSwitchStatus_msg;
extern const pb_msgdesc_t PreferenceProvider_RequestOWStatus_msg;
extern const pb_msgdesc_t PreferenceProvider_Msm2500StatusT_msg;
extern const pb_msgdesc_t PreferenceProvider_CmdStaticHrWarnT_msg;
extern const pb_msgdesc_t PreferenceProvider_BatteryInfo_msg;
extern const pb_msgdesc_t PreferenceProvider_OppoGpsDataCmdT_msg;
extern const pb_msgdesc_t PreferenceProvider_GpsAssistedLocationSwitchT_msg;
extern const pb_msgdesc_t PreferenceProvider_GpsRefLocationT_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PreferenceProvider_OppoSedentaryParamsT_fields &PreferenceProvider_OppoSedentaryParamsT_msg
#define PreferenceProvider_OppoUserProfileParamT_fields &PreferenceProvider_OppoUserProfileParamT_msg
#define PreferenceProvider_OppoActivityStepAimParamT_fields &PreferenceProvider_OppoActivityStepAimParamT_msg
#define PreferenceProvider_OppoActivityCalorieAimParamT_fields &PreferenceProvider_OppoActivityCalorieAimParamT_msg
#define PreferenceProvider_OppoMcuModeT_fields &PreferenceProvider_OppoMcuModeT_msg
#define PreferenceProvider_OppoMcuWorkModeResponseT_fields &PreferenceProvider_OppoMcuWorkModeResponseT_msg
#define PreferenceProvider_OppoTimeProfileParamT_fields &PreferenceProvider_OppoTimeProfileParamT_msg
#define PreferenceProvider_SWITCH_T_fields &PreferenceProvider_SWITCH_T_msg
#define PreferenceProvider_OppoSetSwitchCmdT_fields &PreferenceProvider_OppoSetSwitchCmdT_msg
#define PreferenceProvider_PreferenceBody_fields &PreferenceProvider_PreferenceBody_msg
#define PreferenceProvider_OppoSportsDetectParamsT_fields &PreferenceProvider_OppoSportsDetectParamsT_msg
#define PreferenceProvider_PhoneAirPressureT_fields &PreferenceProvider_PhoneAirPressureT_msg
#define PreferenceProvider_OppoSportsAutopauseParamsT_fields &PreferenceProvider_OppoSportsAutopauseParamsT_msg
#define PreferenceProvider_SyncTimestampT_fields &PreferenceProvider_SyncTimestampT_msg
#define PreferenceProvider_SportHeartrateWarnDataT_fields &PreferenceProvider_SportHeartrateWarnDataT_msg
#define PreferenceProvider_GpsParamsT_fields &PreferenceProvider_GpsParamsT_msg
#define PreferenceProvider_ScreenStatusT_fields &PreferenceProvider_ScreenStatusT_msg
#define PreferenceProvider_ChargeStatusT_fields &PreferenceProvider_ChargeStatusT_msg
#define PreferenceProvider_McuVersion_fields &PreferenceProvider_McuVersion_msg
#define PreferenceProvider_OWSwitch_fields &PreferenceProvider_OWSwitch_msg
#define PreferenceProvider_OWStatus_fields &PreferenceProvider_OWStatus_msg
#define PreferenceProvider_RequestOWSwitchStatus_fields &PreferenceProvider_RequestOWSwitchStatus_msg
#define PreferenceProvider_ResponseOWSwitchStatus_fields &PreferenceProvider_ResponseOWSwitchStatus_msg
#define PreferenceProvider_RequestOWStatus_fields &PreferenceProvider_RequestOWStatus_msg
#define PreferenceProvider_Msm2500StatusT_fields &PreferenceProvider_Msm2500StatusT_msg
#define PreferenceProvider_CmdStaticHrWarnT_fields &PreferenceProvider_CmdStaticHrWarnT_msg
#define PreferenceProvider_BatteryInfo_fields &PreferenceProvider_BatteryInfo_msg
#define PreferenceProvider_OppoGpsDataCmdT_fields &PreferenceProvider_OppoGpsDataCmdT_msg
#define PreferenceProvider_GpsAssistedLocationSwitchT_fields &PreferenceProvider_GpsAssistedLocationSwitchT_msg
#define PreferenceProvider_GpsRefLocationT_fields &PreferenceProvider_GpsRefLocationT_msg

/* Maximum encoded size of messages (where known) */
/* PreferenceProvider_PreferenceBody_size depends on runtime parameters */
/* PreferenceProvider_GpsParamsT_size depends on runtime parameters */
/* PreferenceProvider_McuVersion_size depends on runtime parameters */
#define PREFERENCEPROVIDER_PREFERENCEPROVIDER_PB_H_MAX_SIZE PreferenceProvider_OppoMcuWorkModeResponseT_size
#define PreferenceProvider_BatteryInfo_size      12
#define PreferenceProvider_ChargeStatusT_size    6
#define PreferenceProvider_CmdStaticHrWarnT_size 18
#define PreferenceProvider_GpsAssistedLocationSwitchT_size 6
#define PreferenceProvider_GpsRefLocationT_size  24
#define PreferenceProvider_Msm2500StatusT_size   6
#define PreferenceProvider_OWStatus_size         6
#define PreferenceProvider_OWSwitch_size         6
#define PreferenceProvider_OppoActivityCalorieAimParamT_size 6
#define PreferenceProvider_OppoActivityStepAimParamT_size 6
#define PreferenceProvider_OppoGpsDataCmdT_size  37
#define PreferenceProvider_OppoMcuModeT_size     44
#define PreferenceProvider_OppoMcuWorkModeResponseT_size 86
#define PreferenceProvider_OppoSedentaryParamsT_size 24
#define PreferenceProvider_OppoSetSwitchCmdT_size 19
#define PreferenceProvider_OppoSportsAutopauseParamsT_size 12
#define PreferenceProvider_OppoSportsDetectParamsT_size 12
#define PreferenceProvider_OppoTimeProfileParamT_size 32
#define PreferenceProvider_OppoUserProfileParamT_size 24
#define PreferenceProvider_PhoneAirPressureT_size 16
#define PreferenceProvider_RequestOWStatus_size  6
#define PreferenceProvider_RequestOWSwitchStatus_size 6
#define PreferenceProvider_ResponseOWSwitchStatus_size 6
#define PreferenceProvider_SWITCH_T_size         6
#define PreferenceProvider_ScreenStatusT_size    6
#define PreferenceProvider_SportHeartrateWarnDataT_size 12
#define PreferenceProvider_SyncTimestampT_size   9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
