/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SYSTEMTIME_SYSTEMTIME_PB_H_INCLUDED
#define PB_SYSTEMTIME_SYSTEMTIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SystemTime_req_update_gmt_time_t {
    uint32_t time;
    uint32_t oldTime;
} SystemTime_req_update_gmt_time_t;

typedef struct _SystemTime_req_update_sys_time_t {
    uint32_t time;
    uint32_t oldTime;
    int32_t timezone;
    int32_t oldTimezone;
    uint32_t type;
} SystemTime_req_update_sys_time_t;

typedef struct _SystemTime_req_read_sys_time_t {
    uint32_t type;
} SystemTime_req_read_sys_time_t;

typedef struct _SystemTime_rsp_update_gmt_time_t {
    uint32_t type;
    uint32_t time;
    uint32_t oldTime;
} SystemTime_rsp_update_gmt_time_t;

typedef struct _SystemTime_rsp_read_sys_time_t {
    uint32_t timeSource;
    uint32_t type;
    uint32_t time;
    int32_t timezone;
} SystemTime_rsp_read_sys_time_t;

typedef struct _SystemTime_rsp_sync_summer_timezone_t {
    uint32_t supportSummerTimezone;
    int32_t timezone;
} SystemTime_rsp_sync_summer_timezone_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SystemTime_req_update_gmt_time_t_init_default {0, 0}
#define SystemTime_req_update_sys_time_t_init_default {0, 0, 0, 0, 0}
#define SystemTime_req_read_sys_time_t_init_default {0}
#define SystemTime_rsp_update_gmt_time_t_init_default {0, 0, 0}
#define SystemTime_rsp_read_sys_time_t_init_default {0, 0, 0, 0}
#define SystemTime_rsp_sync_summer_timezone_t_init_default {0, 0}
#define SystemTime_req_update_gmt_time_t_init_zero {0, 0}
#define SystemTime_req_update_sys_time_t_init_zero {0, 0, 0, 0, 0}
#define SystemTime_req_read_sys_time_t_init_zero {0}
#define SystemTime_rsp_update_gmt_time_t_init_zero {0, 0, 0}
#define SystemTime_rsp_read_sys_time_t_init_zero {0, 0, 0, 0}
#define SystemTime_rsp_sync_summer_timezone_t_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SystemTime_req_update_gmt_time_t_time_tag 1
#define SystemTime_req_update_gmt_time_t_oldTime_tag 2
#define SystemTime_req_update_sys_time_t_time_tag 1
#define SystemTime_req_update_sys_time_t_oldTime_tag 2
#define SystemTime_req_update_sys_time_t_timezone_tag 3
#define SystemTime_req_update_sys_time_t_oldTimezone_tag 4
#define SystemTime_req_update_sys_time_t_type_tag 5
#define SystemTime_req_read_sys_time_t_type_tag  1
#define SystemTime_rsp_update_gmt_time_t_type_tag 1
#define SystemTime_rsp_update_gmt_time_t_time_tag 2
#define SystemTime_rsp_update_gmt_time_t_oldTime_tag 3
#define SystemTime_rsp_read_sys_time_t_timeSource_tag 1
#define SystemTime_rsp_read_sys_time_t_type_tag  2
#define SystemTime_rsp_read_sys_time_t_time_tag  3
#define SystemTime_rsp_read_sys_time_t_timezone_tag 4
#define SystemTime_rsp_sync_summer_timezone_t_supportSummerTimezone_tag 1
#define SystemTime_rsp_sync_summer_timezone_t_timezone_tag 2

/* Struct field encoding specification for nanopb */
#define SystemTime_req_update_gmt_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   time,              1) \
X(a, STATIC,   SINGULAR, UINT32,   oldTime,           2)
#define SystemTime_req_update_gmt_time_t_CALLBACK NULL
#define SystemTime_req_update_gmt_time_t_DEFAULT NULL

#define SystemTime_req_update_sys_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   time,              1) \
X(a, STATIC,   SINGULAR, UINT32,   oldTime,           2) \
X(a, STATIC,   SINGULAR, SINT32,   timezone,          3) \
X(a, STATIC,   SINGULAR, SINT32,   oldTimezone,       4) \
X(a, STATIC,   SINGULAR, UINT32,   type,              5)
#define SystemTime_req_update_sys_time_t_CALLBACK NULL
#define SystemTime_req_update_sys_time_t_DEFAULT NULL

#define SystemTime_req_read_sys_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1)
#define SystemTime_req_read_sys_time_t_CALLBACK NULL
#define SystemTime_req_read_sys_time_t_DEFAULT NULL

#define SystemTime_rsp_update_gmt_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   time,              2) \
X(a, STATIC,   SINGULAR, UINT32,   oldTime,           3)
#define SystemTime_rsp_update_gmt_time_t_CALLBACK NULL
#define SystemTime_rsp_update_gmt_time_t_DEFAULT NULL

#define SystemTime_rsp_read_sys_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timeSource,        1) \
X(a, STATIC,   SINGULAR, UINT32,   type,              2) \
X(a, STATIC,   SINGULAR, UINT32,   time,              3) \
X(a, STATIC,   SINGULAR, SINT32,   timezone,          4)
#define SystemTime_rsp_read_sys_time_t_CALLBACK NULL
#define SystemTime_rsp_read_sys_time_t_DEFAULT NULL

#define SystemTime_rsp_sync_summer_timezone_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   supportSummerTimezone,   1) \
X(a, STATIC,   SINGULAR, SINT32,   timezone,          2)
#define SystemTime_rsp_sync_summer_timezone_t_CALLBACK NULL
#define SystemTime_rsp_sync_summer_timezone_t_DEFAULT NULL

extern const pb_msgdesc_t SystemTime_req_update_gmt_time_t_msg;
extern const pb_msgdesc_t SystemTime_req_update_sys_time_t_msg;
extern const pb_msgdesc_t SystemTime_req_read_sys_time_t_msg;
extern const pb_msgdesc_t SystemTime_rsp_update_gmt_time_t_msg;
extern const pb_msgdesc_t SystemTime_rsp_read_sys_time_t_msg;
extern const pb_msgdesc_t SystemTime_rsp_sync_summer_timezone_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SystemTime_req_update_gmt_time_t_fields &SystemTime_req_update_gmt_time_t_msg
#define SystemTime_req_update_sys_time_t_fields &SystemTime_req_update_sys_time_t_msg
#define SystemTime_req_read_sys_time_t_fields &SystemTime_req_read_sys_time_t_msg
#define SystemTime_rsp_update_gmt_time_t_fields &SystemTime_rsp_update_gmt_time_t_msg
#define SystemTime_rsp_read_sys_time_t_fields &SystemTime_rsp_read_sys_time_t_msg
#define SystemTime_rsp_sync_summer_timezone_t_fields &SystemTime_rsp_sync_summer_timezone_t_msg

/* Maximum encoded size of messages (where known) */
#define SYSTEMTIME_SYSTEMTIME_PB_H_MAX_SIZE      SystemTime_req_update_sys_time_t_size
#define SystemTime_req_read_sys_time_t_size      6
#define SystemTime_req_update_gmt_time_t_size    12
#define SystemTime_req_update_sys_time_t_size    30
#define SystemTime_rsp_read_sys_time_t_size      24
#define SystemTime_rsp_sync_summer_timezone_t_size 12
#define SystemTime_rsp_update_gmt_time_t_size    18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
