/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "SystemTime.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemTime_req_update_gmt_time_t, SystemTime_req_update_gmt_time_t, AUTO)


PB_BIND(SystemTime_req_update_sys_time_t, SystemTime_req_update_sys_time_t, AUTO)


PB_BIND(SystemTime_req_read_sys_time_t, SystemTime_req_read_sys_time_t, AUTO)


PB_BIND(SystemTime_rsp_update_gmt_time_t, SystemTime_rsp_update_gmt_time_t, AUTO)


PB_BIND(SystemTime_rsp_read_sys_time_t, SystemTime_rsp_read_sys_time_t, AUTO)


PB_BIND(SystemTime_rsp_sync_summer_timezone_t, SystemTime_rsp_sync_summer_timezone_t, AUTO)



